FRONT-END-BOOTCAMP-PLUS-3/tododong

components/game-status-tag/GameStatusTag.module.scss, components/game-status-tag/GameStatusTag.tsx
✨ feat: GameStatusTag 컴포넌트 추가
- `size`, `status` props 전달에 따른 동적 스타일 적용
resolves #6
=> ✨ feat: GameStatusTag 컴포넌트 추가

components/team/Team.module.scss, components/team/Team.tsx
✨ feat: Team 컴포넌트 추가
- 팀 로고 이미지 URL, name 또는 nickname props 전달
resolves #9
=> ✨ feat: Team 컴포넌트 추가

app/(anon)/login/components/LoginForm.module.scss, app/(anon)/login/components/LoginForm.tsx, app/(anon)/login/page.module.scss, app/(anon)/login/page.tsx, app/(anon)/signup/components/SginupForm.tsx, app/(anon)/signup/components/SignupForm.module.scss, app/(anon)/signup/page.module.scss, app/(anon)/signup/page.tsx, app/api/login/route.ts, app/api/signup/route.ts, app/api/signup/verify/check/route.ts, app/api/signup/verify/route.ts, components/auth-input/AuthInput.module.scss, components/auth-input/AuthInput.tsx, utils/fetcher.ts, utils/formatTime.ts, utils/index.ts
제목을 작성해주세요.
- fetcher 유틸함수 추가했습니다. 기존의 fetch와 동일하게 사용하지만, fetch 요청의 응답 오류와 Loading 컴포넌트 표시를 위한 isLoading 상태를 변경하는 함수를 매개변수로 받아 실행합니다.
- utils -> AuthInput 컴포넌트 -> page 및 Form 컴포넌트의 JSX -> page의 함수들 순서로 봐주세요
- login의 page.tsx를 먼저 보고 구조를 파악한 뒤에 LoginForm을 보면 편할 것 같습니다. -> 그 다음 signup
- route.ts는 page에서 나중에 변경하지 않도록 빼둔 더미데이터를 반환하는 함수들입니다.
Resolves #2
=> ✨ feat: login, signup 페이지 UI 완성

app/(anon)/login/components/LoginForm.module.scss, app/(anon)/login/page.module.scss, app/(anon)/signup/components/SignupForm.module.scss, app/(anon)/signup/page.module.scss, app/layout.tsx, components/auth-input/AuthInput.module.scss, components/header/Header.module.scss, components/header/Header.tsx, components/header/ProfileCard.module.scss, components/header/ProfileCard.tsx, components/modal/Modal.module.scss, hooks/useBodyScrollLock.ts, package.json, pnpm-lock.yaml, stores/authStore.ts, styles/base/_default.scss, styles/base/_reset.scss
Header 컴포넌트 완성
- login 페이지 디자인 오류 수정
- Header, Login페이지, Signup페이지의 요소들 크기를 rem으로 변경 (브라우저 폰트 크기를 변경하니 레이아웃이 깨짐)
- 기능 구현할 때 로그아웃, 계정 삭제 클릭 시 열리는 모달창에서 handleModalConfirm에 쿠키 삭제 및 계정 삭제 로직 추가해야함
- useAuthStore의 User 타입은 추후 변경예정
Resolves #16
=> ✨ feat: Header 컴포넌트 및 authStore

application/usecases/game/migrateScheduleToLocalUsecase.ts, infrastructure/repositories/DfGameRepository.ts, infrastructure/repositories/NbaOfficialGameRepository.ts, prisma/schema.prisma
✨ feat: Game entity에 date 필드 추가 및 startTime, status 필드 수정
- 선택한 날짜별 경기 일정 조회를 위한 Game entity 수정
- UTC ➡️ KST 변환해서 date 필드 추가, startTime 필드 수정
- 1,2,3 ➡️ scheduled, live, final로 변환해서 status 필드 수정
resolves #30
=> ✨ feat: Game entity에 date 필드 추가 및 startTime, status 필드 수정

app/(anon)/game/[game-id]/box-score/components/BoxScoreTable.module.scss, app/(anon)/game/[game-id]/box-score/components/BoxScoreTable.tsx, app/(anon)/game/[game-id]/box-score/page.tsx, app/api/game/[game-id]/box-score/route.ts, application/usecases/game/box-score/dto/boxscoreDto.ts, application/usecases/game/box-score/readBoxscoreUsecase.ts, domain/entities/Statistics.ts, domain/repositories/GameRepository.ts, domain/repositories/StatisticsRepository.ts, domain/repositories/TeamRepository.ts, infrastructure/repositories/DfGameRepository.ts, infrastructure/repositories/DfTeamRepository.ts, infrastructure/repositories/NbaOfficialStatisticsRepository.ts, package.json, pnpm-lock.yaml
Boxscore 데이터 바인딩
- Game 레포지토리 findById 추가
- Team 레포지토리 추가
- Boxscore 레포지토리 추가
- readBoxscoreUsecase 
`game-id` : 0022400061로 들어가보시면 됩니다.
=> ✨ feat : Boxscore 데이터 바인딩

app/(anon)/game/[game-id]/components/chat/ChatSection.module.scss, app/(anon)/game/[game-id]/components/chat/ChatSection.tsx, app/(anon)/game/[game-id]/components/game-status/GameStatusSection.module.scss, app/(anon)/game/[game-id]/components/today/TodayGameCard.module.scss, app/(anon)/game/[game-id]/components/today/TodayGameCard.tsx, app/(anon)/game/[game-id]/layout.module.scss, app/(anon)/schedule/components/game-card/GameCard.module.scss, app/(anon)/schedule/components/game-card/GameCard.tsx, components/game-status-tag/GameStatusTag.module.scss
🎨 design: layout CSS 수정
- 여백 수정
- 채팅, 메인섹션 높이 해상도에 맞춤
- gameCard 승패 점수 색상 구별
=> 🎨 design: layout CSS 수정

app/(anon)/game/[game-id]/components/chat/ChatSection.module.scss, app/(anon)/game/[game-id]/components/chat/ChatSection.tsx, app/(anon)/game/[game-id]/components/game-status/GameStatusSection.module.scss, app/(anon)/game/[game-id]/components/game-status/GameStatusSection.tsx, app/(anon)/game/[game-id]/components/today/TodayGameCard.module.scss, app/(anon)/game/[game-id]/components/today/TodayGameCard.tsx, app/(anon)/game/[game-id]/components/today/TodayGameSection.tsx, app/(anon)/game/[game-id]/layout.module.scss, app/(anon)/game/[game-id]/layout.tsx, app/api/game/[game-id]/route.ts, application/usecases/game/game-detail/dto/gameDetailDto.ts, application/usecases/game/game-detail/getGameDetailUsecase.ts, components/game-status-tag/GameStatusTag.module.scss, domain/repositories/NbaGameRepository.ts, infrastructure/repositories/nbaOfficial/NbaOfficialGameRepository.ts
✨ feat: 경기 상세 데이터 바인딩
- 레이아웃에 경기 데이터 패치 후 GameStatusSection, ChatSection에 전달
- TodayGameSection 데이터 바인딩
=> ✨ feat: 경기 상세 데이터 바인딩

app/(anon)/game/[game-id]/components/chat/ChatSection.tsx, app/(anon)/game/[game-id]/components/today/TodayGameCard.tsx, app/(anon)/game/[game-id]/layout.module.scss
🐛 Fix : 채팅 수정
- textarea rows 지정해서 렌더링 시 높이 변경 수정
=> 🐛 Fix : 상세페이지 CSS 수정

.github/workflows/deploy-on-ubuntu-server.yml
🔧 chore: Create deploy-on-ubuntu-server.yml
- deploy-on-ubuntu-server.yml 작성
=> 🔧 chore: Create deploy-on-ubuntu-server.yml

.github/workflows/deploy-on-ubuntu-server.yml
🔧 chore: Update deploy-on-ubuntu-server.yml
- deploy-on-ubuntu-server.yml에 run을 next-app-update.sh를 실행하도록 변경
=> 🔧 chore: Update deploy-on-ubuntu-server.yml

app/(anon)/game/[game-id]/play-by-play/components/Timeline.module.scss
🎨 design: Timeline 점수 width 수정
- Timeline 점수 width 수정
=> 🎨 design: Timeline 점수 width 수정

app/(anon)/game/[game-id]/layout.tsx, app/(anon)/login/page.tsx, app/(anon)/schedule/layout.tsx, app/(anon)/signup/page.tsx, app/layout.tsx
🔧 chore : 페이지 별 metadata 작성
- 페이지 별 metadata 작성
- `RootLayout`의 description 수정
- `Login`, `Signup` 페이지 metadata 추가
- `Schedule` 페이지는 CSR이기 때문에 `ScheduleLayout` 추가
- `GameLayout`에 동적 metadata 추가
=> 🔧 chore : 페이지 별 metadata 작성

app/(anon)/schedule/components/date-picker/DatePicker.module.scss, app/(anon)/schedule/components/date-picker/DatePicker.tsx, app/(anon)/schedule/components/date-picker/calendar-custom.scss, app/(anon)/schedule/components/game-card/GameCard.module.scss, app/(anon)/schedule/page.module.scss, components/footer/Footer.module.scss, components/game-status-tag/GameStatusTag.module.scss, components/header/Header.module.scss, components/team/Team.module.scss, styles/base/_default.scss, styles/utils/_mixins.scss, styles/utils/_variables.scss
🎨 design: 반응형 디자인 추가
- Sass 믹스인 적용
```scss
// 미디어쿼리 중단점
$breakpoints: (
smMobile: 480,
lgMobile: 768,
tablet: 1279,
);
// 사용 예시
// @include mq(tablet) {
//   .test {
//     width: 100%;
//   }
// }
```
- schedule 페이지
- Header, Footer 컴포넌트
resolves #65
=> 🎨 design: 반응형 디자인 추가

app/(anon)/game/[game-id]/layout.module.scss, app/(anon)/game/[game-id]/layout.tsx, app/(anon)/game/[game-id]/videos/components/YoutubeVideoCard.module.scss, app/(anon)/game/[game-id]/videos/components/YoutubeVideoCard.tsx, app/(anon)/game/[game-id]/videos/page.module.scss, app/(anon)/game/[game-id]/videos/page.tsx, app/layout.tsx, components/query-provider/QueryProvider.tsx, package.json, pnpm-lock.yaml, styles/utils/_mixins.scss
♻️ refactor : 비디오 페이지 react-query 및 반응형 추가
- `QueryProvider` 컴포넌트 추가
`ReactQueryDevtools`도 같이 추가했습니다. 브라우저 오른쪽 하단에 버튼 클릭하면 Query Details 확인할 수 있습니다.
- 비디오 데이터의 최신 상태를 1시간으로 설정
- 반응형 디자인 추가
=> ♻️ refactor : 비디오 페이지 react-query 및 반응형 추가

app/(anon)/game/[game-id]/box-score/components/BoxScoreTable.tsx, app/(anon)/game/[game-id]/box-score/page.module.scss, app/(anon)/game/[game-id]/box-score/page.tsx, app/(anon)/game/[game-id]/layout.module.scss, app/(anon)/game/[game-id]/layout.tsx, app/(anon)/game/[game-id]/play-by-play/page.module.scss, app/(anon)/game/[game-id]/videos/components/YoutubeVideoCard.module.scss, app/(anon)/game/[game-id]/videos/components/YoutubeVideoCard.tsx, app/(anon)/game/[game-id]/videos/page.module.scss, app/(anon)/game/[game-id]/videos/page.tsx, app/layout.tsx, components/query-provider/QueryProvider.tsx, package.json, pnpm-lock.yaml, styles/utils/_mixins.scss
♻️ refactor : 박스스코어 페이지 react-query 및 반응형 추가
- feature/vidoes 브랜치에서 분기
- 반응형, react-query 추가
=> ♻️ refactor : 박스스코어 페이지 react-query 및 반응형 추가

app/(anon)/game/[game-id]/layout.module.scss, app/(anon)/game/[game-id]/layout.tsx, app/(anon)/game/[game-id]/play-by-play/page.module.scss, app/(anon)/game/[game-id]/videos/components/YoutubeVideoCard.module.scss, app/(anon)/game/[game-id]/videos/components/YoutubeVideoCard.tsx, app/(anon)/game/[game-id]/videos/page.module.scss, app/(anon)/game/[game-id]/videos/page.tsx, app/layout.tsx, components/query-provider/QueryProvider.tsx, package.json, pnpm-lock.yaml, styles/utils/_mixins.scss
♻️ refactor : 실시간 중계 페이지 반응형 추가
- feature/videos 브랜치에서 분기
- 반응형에 맞게 스타일 수정
=> ♻️ refactor : 실시간 중계 페이지 반응형 추가

app/(anon)/layout.tsx, app/layout.tsx, components/footer/Footer.tsx, components/header/Header.tsx
♻️ refactor : Header, Footer 렌더링 여부 로직 위치 변경
- Header, Footer 렌더링 여부 로직 위치를 `컴포넌트 내부` → `Layout`으로 변경
=> ♻️ refactor : Header, Footer 렌더링 여부 로직 위치 변경

app/(anon)/game/[game-id]/components/chat/ChatSection.module.scss, app/(anon)/game/[game-id]/components/game-status/GameStatusSection.module.scss, app/(anon)/game/[game-id]/components/game-status/GameStatusSection.tsx, app/(anon)/game/[game-id]/components/providers/ReactQueryProviders.tsx, app/(anon)/game/[game-id]/components/today/TodayGameCard.module.scss, app/(anon)/game/[game-id]/components/today/TodayGameSection.module.scss, app/(anon)/game/[game-id]/components/today/TodayGameSection.tsx, app/(anon)/game/[game-id]/components/today/swiper.scss, app/(anon)/game/[game-id]/layout.tsx, application/usecases/game/game-detail/dto/gameDetailDto.ts, application/usecases/game/game-detail/getGameDetailUsecase.ts
react-query, 실시간 데이터, 반응형 작업
- 오늘의 경기 fetcher를 react-query로 변경
- layout 반응형 디자인 추가
- gamsStatusSection 실시간 데이터로 변경
=> ♻️ refactor: react-query, 실시간 데이터, 반응형 작업

.github/workflows/deploy-on-ubuntu-server.yml
Github Actions에서 배포 수동 실행 가능하도록 수정
- Github Actions에서 배포 수동 실행 가능하도록 수정
=> Github Actions에서 배포 수동 실행 가능하도록 수정
